name: Deploy Web to Server
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy a servidor LXC
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          port: 2222
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            git pull origin master